-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.4

local tab = {
	WordSleep = {
		{ Key = 0, SleepInterval = { Day= 1, Hour= 0, Minute= 0, Second= 0 } 	},
		{ Key = 1, SleepInterval = { Day= 2, Hour= 0, Minute= 0, Second= 0 } 	},
		{ Key = 2, SleepInterval = { Day= 5, Hour= 0, Minute= 0, Second= 0 } 	},
		{ Key = 3, SleepInterval = { Day= 8, Hour= 0, Minute= 0, Second= 0 } 	},
		{ Key = 4, SleepInterval = { Day= 14, Hour= 0, Minute= 0, Second= 0 } 	},
		{ Key = 5, SleepInterval = { Day= 31, Hour= 0, Minute= 0, Second= 0 } 	}
	}

}


-- Key
tab.WordSleepByKey = {}
for _, rec in pairs(tab.WordSleep) do
	tab.WordSleepByKey[rec.Key] = rec
end

tab.Enum = {
}

return tab